services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    environment:
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_CACHE=ispn # Use infinispan caching
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloakdb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
      - KC_LOG_LEVEL=INFO,org.infinispan:INFO,org.jgroups:INFO
    ports:
      - "8080:8080"
    command: start-dev
